import{a as y,S as h,i as g}from"./assets/vendor-b11e2a50.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const v="https://pixabay.com/api/",L="44807177-c49104cccf7249c598a5adf77";async function b(e,n=1,r=15){try{return(await y.get(v,{params:{key:L,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:n,per_page:r}})).data}catch(s){throw console.error("Fetch error: ",s),s}}let u;function w(e){const n=document.querySelector(".gallery"),r=e.map(s=>S(s)).join("");n.insertAdjacentHTML("beforeend",r),u?u.refresh():u=new h(".gallery a"),q()}function S(e){return`
    <div class="image-card">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      </a>
      <div class="info">
        <div> <p>Likes: <p>${e.likes}</p></p></div>
        <div><p>Views: <p>${e.views}</p></p></div>
        <div><p>Comments: <p>${e.comments}</p></p></div>
        <div> <p>Downloads: <p>${e.downloads}</p></p></div>
      </div>
    </div>
  `}function q(){const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function p(){const e=document.querySelector(".gallery");e.innerHTML=""}function i(e){g.error({message:e,messageColor:"#fff",position:"topRight",color:"#ef4040"})}function P(){const e=document.createElement("div");e.classList.add("loader"),document.body.appendChild(e)}function f(){const e=document.querySelector(".loader");e&&e.remove()}let l=1,c="";const C=document.querySelector("#search-form"),E=document.querySelector("#search-input"),a=document.createElement("button");a.classList.add("btn","load-more");a.textContent="Load more";a.style.display="none";document.body.appendChild(a);C.addEventListener("submit",e=>{e.preventDefault(),I()});a.addEventListener("click",()=>{l+=1,m(c,l)});async function I(){if(c=E.value.trim(),!c){i("Please enter a search term");return}l=1,p(),a.style.display="none",await m(c,l)}async function m(e,n){P();try{const r=await b(e,n);f(),r.hits.length===0?i("Sorry, there are no images matching your search query. Please try again!"):(w(r.hits),r.totalHits>n*15?a.style.display="block":(a.style.display="none",i("We're sorry, but you've reached the end of search results.")))}catch(r){f(),p(),i("Failed to fetch images. Please try again later."),console.error("Fetch error: ",r)}}
//# sourceMappingURL=commonHelpers.js.map
